from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('callback/', views.callback, name='callback'),
    path('token/', views.token, name='token'),
    path('accounts/', views.accounts_view, name='accounts'),
    path('accounts/switch/', views.switch_account_view, name='switch_account'),
    path('accounts/remove/', views.remove_account_view, name='remove_account'),
    path('search/', views.search, name='search'),
    path('devices/', views.devices, name='devices'),
    path('current-playback/', views.current_playback, name='current_playback'),
    path('transfer/', views.transfer_device, name='transfer'),
    path('select-web-player/', views.select_web_player, name='select_web_player'),
    path('play/', views.play, name='play'),
    path('pause/', views.pause, name='pause'),
    path('next/', views.next_track, name='next'),
    path('previous/', views.previous_track, name='previous'),
    path('seek/', views.seek, name='seek'),
    path('queue/', views.queue_track, name='queue'),
    path('play-track/', views.play_track, name='play_track'),
    path('playlists/', views.playlists, name='playlists'),
    path('playlist-detail/', views.playlist_detail, name='playlist_detail'),
    path('play-playlist/', views.play_playlist, name='play_playlist'),
    path('albums/', views.albums, name='albums'),
    path('album-detail/', views.album_detail, name='album_detail'),
    path('play-album/', views.play_album, name='play_album'),
    path('saved-tracks/', views.saved_tracks, name='saved_tracks'),
    path('discover/', views.discover, name='discover'),
    path('settings/', views.settings_view, name='settings'),
    path('settings/audio/', views.update_audio_settings, name='update_audio_settings'),
    path('settings/reboot/', views.reboot_system, name='reboot_system'),
]